# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160621_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_enrollment',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='max_enrollment',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
