# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160621_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='restrictions',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='wait_list',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='websoc_url',
            field=models.URLField(default=''),
        ),
    ]
