# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
        ),
    ]
