# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160623_1338'),
        ('courses', '0011_auto_20160623_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='courserequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='websoc_url',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to='authentication.UserProfile'),
        ),
        migrations.DeleteModel(
            name='CourseRequest',
        ),
    ]
