# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160621_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='course',
            name='wait_list',
        ),
    ]
