# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160621_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='restrictions',
            field=models.CharField(max_length=5),
        ),
    ]
