# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160623_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_view', 'Can View'), ('can_modify', 'Can Modify'))},
        ),
    ]
